[project]
name = "modular-search"
version = "0.1.7"
description = "A Modular Search Framework for Military Developers"
readme = "README.md"
authors = [
    { name = "Prannaya Gupta", email = "prannayagupta@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "googlesearch-python>=1.3.0",
    "pydantic>=2.11.5",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
