jobs: "30"
max-jobs-per-second: "10"
max-status-checks-per-second: "10"
local-cores: 44
latency-wait: "30"
# use-conda: "True"
printshellcmds: "True"
rerun-incomplete: "False"
keep-incomplete: "True"

# default-resources:
#   - runtime=100
#   - mem_mb=6000
#   - disk_mb=1000000