[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "factverifai"
version = "0.1.5"
description = "AI-powered fact-checking Python library"
authors = [{ name = "Your Name", email = "iliescuaf@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.13"
dependencies = [
    "ipykernel",
    "openai",
    "ollama",
    "exa_py",
    "python-dotenv",
    "langchain",
    "langgraph",
    "langchain_community",
    "langchain-ollama",
    "langchain-exa",
    "requests"
]

[project.urls]
Homepage = "https://github.com/a-i-flo/factverifai"

[tool.setuptools.packages.find]
where = ["."]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
