[project]
name = "ssh-mcp"
version = "0.1.2"
description = "SSH MCP - tools for remote SSH operations for debugging"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}
authors = [
    {name = "czyhandsome", email = "czyhandsome@foxmail.com"},
]
keywords = ["protocol", "mcp", "server", "ssh", "remote"]
dependencies = [
    "paramiko>=3.4.0",
    "mcp-python>=0.1.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mcpssh"]

[project.scripts]
ssh-mcp = "mcpssh.main:main" 
