[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pywarper"
version = "0.1.6"
description = "Conformal mapping-based warping of neuronal arbor morphologies."
authors = []
requires-python = ">=3.10.0"
dependencies = [
    "alphashape>=1.3.1",
    "numpy>=2.0.2",
    "pandas>=2.2.3",
    "pygridfit>=0.1.4",
    "scipy>=1.13.1",
    "skeliner>=0.1.0",
    "watermark>=2.5.0",
]
readme = {file = "README.md", content-type = "text/markdown"}

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest",
    "twine",
    "maturin",
    "ipykernel>=6.29.5",
]
scikit-sparse = [
    "scikit-sparse>=0.4.15",
    "pygridfit[scikit-sparse]>=0.1.4"
]

[tool.setuptools]
packages = {find = {}}
include-package-data = true
