[project]
name = "mywigle"
version = "0.3.0"
description = "mywigle is a wrapper for the WiGLE WiFi mapping API"
authors = [
    { name = "tct123", email = "42028373+tct123@users.noreply.github.com" },
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["requests (>=2.32.3,<3.0.0)"]

[tool.poetry]
packages = [{ include = "mywigle", from = "src" }]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
