# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nlp4bia"
version = "2.4.1"
description = "Download NLP4BIA benchmarks and load datasets in their format"
readme = "README.md"
authors = [{ name = "Alberto Becerra", email = "alberto.becerra.tome@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["feed", "reader", "tutorial"]
dependencies = [
    "pandas>=2.0.0",
    "requests>=2.32.3",
    "tqdm>=4.67.0",
    'tomli; python_version < "3.11"',
    'pymupdf4llm>=0.0.17',
    'markdown>=3.3.4',
    'sentence-transformers>=4.1.0',
    'torch>=2.6.0'
]

requires-python = ">=3.7"

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

# [project.urls]
# Homepage = "https://github.com/realpython/reader"

# [project.scripts]
# realpython = "reader.__main__:main"
[tool.bumpver]
current_version = "2.4.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message  = "Bump version {old_version} -> {new_version}"
commit          = true
tag             = true
push            = false

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
"nlp4bia/__init__.py" = ["{version}"]

[tool.setuptools.packages.find]
# include = ["nlp4bia", "nlp4bia.datasets", "nlp4bia.datasets.*"]
exclude = ["nbs"]
