[project]
name = "requests-oauthlib-uma"
description = "UMA 2.0 session and client support for requests-oauthlib"
authors = [{ name = "Dave Sutherland", email = "dave@daveography.ca" }]
license = "MIT"
readme = "README.md"
packages = [{include = "requests_oauthlib_uma"}]
keywords = ["requests", "oauthlib", "oauth2", "user-managed access", "uma", "uma2", "uma2.0"]
requires-python = ">=3.9"
dynamic = [ "version" ]
dependencies = [
    "requests-oauthlib>=2.0.0",
    "typing-extensions>=4.12.2",
    "tenacity>=9.0.0",
]

[project.urls]
repository = "https://github.com/Daveography/requests-oauthlib-uma"

[tool.poetry]
version = "v0.1.2"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
pre-commit = "^3.2.1"
pytest = "^8.2.2"
black = "^24.3"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
exclude = '''
/(
    \.git
    | __pycache__
    | \.venv
    | build
    | dist
)/
'''

[tool.isort]
profile = "black"
lines_between_sections = 1
line_length = 120
multi_line_output = 3
sections = ["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
extra_standard_library = ["typing_extensions"]

[tool.pytest.ini_options]
testpaths = ["tests"]
