[project]
name = "quarto-lib"
version = "0.1.3"
description = "Common library for Quarto-Games projects."
authors = [
    { name = "patapelada", email = "77882237+patapelada@users.noreply.github.com" },
]
dependencies = []
requires-python = "==3.13.*"
readme = "README.md"
license = "MIT"
license-files = [
    "LICEN[CS]E*",
]

[project.urls]
Homepage = "https://github.com/patapelada/quarto-lib"
Issues = "https://github.com/patapelada/quarto-lib/issues"

[tool.pdm]
distribution = true

[build-system]
requires = [
    "pdm-backend >= 2.4.0",
]
build-backend = "pdm.backend"
