[build-system]
requires = ["setuptools >= 61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "randextract"
version = "0.2.0"
description = "A reference implementation for testing & validating Privacy Amplification algorithms"
authors = [
    {name = "Esther Hänggi", email = "esther.haenggi@hslu.ch"},
    {name = "Iyán Méndez Veiga", email = "iyan.mendezveiga@hslu.ch"},
]
dependencies = [
    "numpy >= 1.21.0",
    "galois >= 0.3.6",
    "scipy >= 1.12",
    "gmpy2 >=2.2.0a1, <3",
    "termcolor >= 2.4",
]
requires-python = ">=3.10, <3.14"
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
keywords = ["Quantum Cryptography", "Randomness Extractor", "Privacy Amplification"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://randextract.crypto-lab.ch"
Issues = "https://github.com/cryptolab/randextract/issues"

[project.optional-dependencies]
dev = [
    "black",
    "build",
    "isort",
    "jupyterlab",
    "matplotlib",
    "twine",
]
docs = [
    "Sphinx",
    "sphinx-book-theme",
    "sphinxcontrib-bibtex",
    "sphinx-togglebutton",
    "sphinx-tabs",
    "sphinx-autodoc-typehints",
]
examples = [
    "pyzmq",
]
test = [
    "pytest",
    "pytest-cov",
]
all = ["randextract[dev,docs,examples,test]"]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
