[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "prune_libs"
version = "1.20.0"
description = "Python libraries for Prune."
readme = "README.md"
requires-python = ">=3.12,<4.0"
authors = [{ name = "Arnout", email = "bastien@prune.sh" }]
keywords = ["captcha", "django", "code-quality"]
urls = { Made_by = "https://prune.sh/" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "django>=5.2",
    "pydantic>=2.11.3",
    "sendgrid>=6.11.0",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"prune_captcha" = ["templates/**/*", "static/**/*"]

[tool.setuptools.packages.find]
where = ["."]
