[project]
name = "conndoc"
version = "0.2.1"
description = "Diagnose connectivity and infrastructure issues from the CLI"
authors = [{ name = "Mert Acikportali", email = "mertacikportali@gmail.com" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "rich (>=14.0.0,<15.0.0)",
    "typer (>=0.16.0,<0.17.0)",
    "httpx (>=0.28.1,<0.29.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
conndoc = "conndoc.cli:app"
