[project]
name = "songlink"
version = "v1-alpha.1-rev-1"
description = "An unofficial lightweight, type hinted library that helps query the songlink api: https://odesli.co/"
authors = [
    {name = "Flinty", email = "blobjo7@gmail.com"}
]
readme = "README.md"
license = "MIT"
license-files = "License"
url = "https://github.com/Intyflay/songlink"
requires-python = ">=3.9"
dependencies = [
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"