[project]
name = "EasyPythonNO"
version = "0.0.1"
description = "Easy Version Of Python!"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [{ name = "SH_Dev", email = "sh-dev@luna-tools.store" }]
