[project]
name = "fermi-cref"
version = "0.1.0"
description = "FitnEss Relatedness and other MetrIcs"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.9"

authors = [
  { name = "Aurelio Patelli", email = "aurelio.patelli@cref.it" },
  { name = "Riccardo Piombo", email = "riccardo.piombo@cref.it" },
  { name = "Matteo Straccamore", email = "matteo.straccamore@cref.it" },
  { name = "Lorenzo Buffa", email = "lorenzo.buffa@cref.it" },
  { name = "Daniele Cirulli", email = "daniele.cirulli@cref.it" },
  { name = "Filippo Santoro", email = "filippo.santoro@cref.it" },
  { name = "Valeria Secchini", email = "valeria.secchini@cref.it" },
  { name = "Dario Mazzilli", email = "dario.mazzilli@cref.it" },
]

dependencies = [
  "numpy>=1.24",
  "pandas>=1.5",
  "matplotlib>=3.5",
  "scipy>=1.9",
  "networkx>=2.6",
  "bokeh>=2.4",
  "tqdm>=4.64",
  "scikit-learn>=1.2",
  "bicm>=3.3.1",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/EFC-data/fermi"
"Bug Tracker" = "https://github.com/EFC-data/fermi/issues"
