[project]
name = "trustpoint-core"
version = "0.2.1"
description = "Trustpoint core functionalities used by several other Trustpoint repositories."
requires-python = ">=3.12"
dependencies = [
    "cryptography>=44.0.3",
    "hatchling>=1.27.0",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pytest>=8.3.5",
    "pytest-html>=4.1.1",
    "pytest-md-report>=0.7.0",
    "ruff>=0.11.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "double"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812",   # Not compatible with the formatter
]

[tool.ruff.lint.per-file-ignores]
"**/tests/**/**.py" = ["S101"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = ["crispy_bootstrap5.*", "crispy_forms.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = 'trustpoint.settings'
python_files = 'test_*.py'
md_report = true
md_report_output = 'md-report.md'
