[project]
name = "sankalp-deepak"
version = "0.1.0"
description = "This is a cli tool to organize tasks"
authors = [
    {name = "Deepak Prakash", email = "deepak.prakash@flipkart.com"}
]
readme = "README.md"

[tool.poetry]
packages = [
    {include = "sankalp"}
]

[tool.poetry.scripts]
sankalp = "sankalp.main:app"

[tool.poetry.dependencies]
python = ">=3.9.0,<4.0"
apscheduler = "3.11.0"
async-timeout = "5.0.1"
black = "25.1.0"
click = "8.1.8"
markdown-it-py = "3.0.0"
mdurl = "0.1.2"
mypy = "1.16.0"
mypy-extensions = "1.1.0"
packaging = "25.0"
pathspec = "0.12.1"
peewee = "3.18.1"
peewee-migrate = "1.13.0"
platformdirs = "4.3.8"
poetry-core = "2.1.3"
psycopg2-binary = "2.9.9"
pygments = "2.19.1"
pync = "2.0.3"
python-dateutil = "2.9.0.post0"
rich = {version = "14.0.0", markers = "python_version >= '3.8.0'"}
shellingham = "1.5.4"
six = "1.17.0"
sqlalchemy = "2.0.41"
tomli = "2.2.1"
typer = "0.16.0"
types-peewee = "3.18.1.20250516"
typing-extensions = "4.13.2"
tzlocal = "5.3.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
