[project]
name = "django-cascade-filter"
version = "0.1.0-rc4"
description = "Cascade filters in the Django Admin Panel"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "arrow>=1.3.0",
    "django>=3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
