[project]
name = "dell-ai"
version = "0.1.4"
description = "Python SDK and CLI for interacting with the Dell Enterprise Hub (DEH)"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
maintainers = [
  {name = "Andrew Reed", email = "andrew.reed@huggingface.co"},
  {name = "Alvaro Bartolome", email = "alvaro.bartolome@huggingface.co"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: Apache Software License",
]
dependencies = [
    "requests>=2.31.0",
    "typer>=0.9.0",
    "pydantic>=2.5.0",
    "huggingface-hub>=0.30.2",
]
scripts = { "dell-ai" = "dell_ai.cli.main:app" }
urls = { Repository = "https://github.com/huggingface/dell-ai", Homepage = "https://dell.huggingface.co/" }

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-mock>=3.10.0",
    "pytest-cov>=4.1.0",
    "black>=23.3.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "ipykernel>=6.29.5",
    "bump2version>=1.0.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["dell_ai"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=dell_ai --cov-report=term-missing"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning"
]

[tool.coverage.run]
source = ["dell_ai"]
omit = ["tests/*", "**/__init__.py"]