[project]
name = "yamlcleaner"
version = "0.1.1"
description = "Un outil CLI pour nettoyer les fichiers YAML en supprimant les commentaires"
authors = [{ name = "Funasitien", email = "hello@funa.dev" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.7"
dependencies = ["colorama"]

[project.scripts]
yamlcleaner = "yamlcleaner.cli:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
