[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tetrad_plus"
version = "0.1.4"
authors = [
  { name = "Kelvin O. Lim", email = "lim.kelvino@gmail.com" },
]
description = "A package of tools for working with the tetrad java program for causal discovery from CMU"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
# This is the correct way to list runtime dependencies directly under [project]
dependencies = [
    "JPype1",
    "pandas",
    "python-dotenv",
    "PyYAML",
    "seaborn",
    "semopy",
    "graphviz",
    "tqdm",
    "ipykernel",
    "dgraph_flex",
    "ipywidgets",
    "scikit-learn",
    "ipython",
    "ipykernel",
    "matplotlib",

]

[project.urls]
"Homepage" = "https://github.com/kelvinlim/tetrad_plus"
"Bug Tracker" = "https://github.com/kelvinlim/tetrad_plus/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["tetrad_plus*"]

[tool.setuptools.package-data]
"tetrad_plus" = ["jars/*.jar","data/*.csv","data/*.txt"]
