[project]
name = "docsray"
version = "1.3.1"
description = "PDF Question-Answering System with MCP Integration"
authors = [{name = "Taehoon Kim", email = "taehoonkim@sogang.ac.kr"}]
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}

dependencies = [
    "PyMuPDF",
    "pdfplumber",
    "tiktoken",
    "torch",
    "protobuf",
    "fastapi",
    "uvicorn",
    "mcp",
    "numpy",
    "pandas",
    "pillow",
    "scikit-learn",
    "opencv-python",
    "psutil",
    "llama-cpp-python",
    "gradio",
    "pypandoc>=1.11",
    "python-docx>=0.8.11",
    "docx2pdf>=0.1.8",
    "openpyxl>=3.0.10",
    "python-pptx>=0.6.21",
    "pdfkit>=1.0.0",
    "markdown>=3.4.1",
    "pyhwp",
    "olefile",
    "reportlab",
    "Pandoc",
    "wkhtmltopdf"
]

[project.scripts]
docsray = "docsray.cli:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["docsray"]
include-package-data = true

[tool.setuptools.package-data]
docsray = ["data/*"]