[project]
name = "langbot-plugin"
version = "0.1.0-alpha.1"
description = "This package contains the SDK, CLI for building plugins for LangBot, plus the runtime for hosting LangBot plugins"
readme = "README.md"
authors = [
    { name = "Junyan Qin", email = "rockchinq@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "mypy>=1.16.0",
    "pydantic>=2.11.5",
    "ruff>=0.11.12",
    "textual>=3.2.0",
    "websockets>=15.0.1",
]

[project.scripts]
lbp = "langbot_plugin.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
Homepage = "https://langbot.app"
Repository = "https://github.com/langbot-app/langbot-plugin-sdk"
Issues = "https://github.com/langbot-app/langbot-plugin-sdk/issues"