[project]
name = "rcabench-platform"
version = "0.1.14"
description = "An experiment framework for Root Cause Analysis"
readme = "README.md"
authors = [
    { name = "Nugine", email = "xuyangwang@link.cuhk.edu.cn" }
]
requires-python = ">=3.12"
dependencies = [
    "clickhouse-connect>=0.8.17",
    "huggingface-hub>=0.32.3",
    "kubernetes>=32.0.1",
    "loguru>=0.7.3",
    "marimo[recommended]>=0.13.15",
    "minio>=7.2.15",
    "mysql-connector-python>=9.3.0",
    "neo4j>=5.28.1",
    "networkx>=3.5",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "plotly>=6.1.2",
    "pyarrow>=20.0.0",
    "rcabench>=1.0.9",
    "requests>=2.32.3",
    "scipy>=1.15.3",
    "tqdm>=4.67.1",
    "typer>=0.16.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
cache-dir = ".cache/ruff"
line-length = 120

[tool.ruff.lint]
select = [
    "UP", # https://docs.astral.sh/ruff/rules/#pyupgrade-up
]
ignore = ["UP038"]

[tool.pyright]
exclude = [ #
    ".git",
    "**/__pycache__",
    ".cache",
    ".idea",
    ".vscode",
    ".venv",
    ".devbox",
    "db/",
    "data/",
    "temp/",
    "logs/",
    "vendor/",
    "output/",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "kubernetes-stubs-elephant-fork>=32.0.1",
    "pyright>=1.1.401",
    "ruff>=0.11.12",
]
