[project]
name = "cnoe-agent-utils"
version = "0.1.3"
description = ""
authors = [
    {name = "Sri Aradhyula",email = "sraradhy@cisco.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "dotenv (>=0.9.9,<0.10.0)",
    "langchain-anthropic>=0.3.14",
    "langchain-aws (>=0.2.24,<0.3.0)",
    "langchain-google-genai>=2.1.5",
    "langchain-google-vertexai>=2.0.24",
    "langchain-openai>=0.3.18",
    "google-auth (>=2.40.2,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
