[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "XMFlib"
version = "0.1.1"
description = "A library for pair probability prediction using machine learning."
authors = [
    { name="Minhui Li", email="23210220016@m.fudan.edu.cn" }
]
readme = "readme.md"
license = { file = "LICENCE" }
requires-python = ">=3.7"
dependencies = [
    "torch>=1.10"
]

[project.urls]
Homepage = "https://github.com/aFui233/XMFlib"
Repository = "https://github.com/aFui233/XMFlib"

[tool.setuptools.packages.find]
where = ["."]
include = ["PairProbML*"]